import type { AgentStatusBarView, ProjectDocument } from "@/contracts/creator";

export const status: AgentStatusBarView = {
  progress: {
    phase: "timeline_render",
    label: "正在渲染 Timeline",
    sourceEventSeq: 1,
    updatedAt: "2026-07-10T00:00:00Z",
  },
  badges: [],
};

const defaultLocation = {
  coordinate_space: "normalized_canvas" as const,
  x: 0.5,
  y: 0.5,
  width: 1,
  height: 1,
  anchor_x: 0.5,
  anchor_y: 0.5,
  rotation_degrees: 0,
  opacity: 1,
};

/** Schema-v4 Project fixture used by the Timeline/Element frontend. */
export const projectDocument: ProjectDocument = {
  schema_version: 4,
  project_id: "p1",
  generation: 3,
  created_at: "2026-07-20T00:00:00Z",
  updated_at: "2026-07-20T00:02:00Z",
  name: "测试项目",
  description: "一支由重叠 Element 组成的测试短片",
  scenario: "general",
  settings: {
    aspect_ratio: "16:9",
    resolution: "1080P",
    platform: "web",
    language: "zh-CN",
    target_duration_seconds: 20,
    content_type: "video",
  },
  strategy: {
    creative_brief: "一只橘猫从清晨出发，最后在星光下回家。",
    audience: "爱猫用户",
    creative_direction: "温暖、轻快、电影感",
    constraints: "",
    success_criteria: "20 秒内讲完整故事",
  },
  sources: {
    sources: {
      order: ["source:cat-video"],
      items: {
        "source:cat-video": {
          source_id: "source:cat-video",
          display_name: "橘猫原始视频",
          logical_asset_id: "asset:cat-video",
          selected_asset_version_id: "cat-video-v1",
          current_intelligence_version_id: null,
          user_notes: "",
        },
      },
    },
  },
  visual: {
    visual_bible: "橘猫保持圆润体型和红色项圈。",
    style: "暖色电影感",
    entities: {
      order: ["cat"],
      items: {
        cat: {
          entity_id: "cat",
          kind: "character",
          name: "圆润大橘猫",
          description: "主角，佩戴红色项圈",
          continuity: "所有画面保持同一项圈与毛色",
          required_variant_ids: ["variant:cat:default"],
          variants: {
            order: ["variant:cat:default"],
            items: {
              "variant:cat:default": {
                variant_id: "variant:cat:default",
                requirements: "圆润体型、橘色毛发、红色项圈",
                prompt: "圆润大橘猫，佩戴红色项圈",
                reference_asset_version_ids: [],
                reference_artifact_version_ids: [],
                generated_artifact_version_ids: ["cat-anchor-v1"],
                selected_artifact_version_id: "cat-anchor-v1",
              },
            },
          },
          selected_artifact_version_id: "cat-anchor-v1",
        },
      },
    },
  },
  timelines: {
    order: ["timeline:main"],
    items: {
      "timeline:main": {
        timeline_id: "timeline:main",
        ticks_per_second: 1000,
        elements_by_id: {
          "edit-opening": {
            element_id: "edit-opening",
            label: "开场 · 晨光中的小猫",
            enabled: true,
            span: { start_tick: 0, duration_tick: 8000 },
            location: defaultLocation,
            z_index: 0,
            creation: {
              type: "edit",
              intent: "从原素材截取开场",
              reason: "建立环境和主角",
              original_sound: "preserve",
              source_intelligence_version_id: null,
            },
            outputs: {},
            render_source: {
              type: "source_asset_version",
              version_id: "cat-video-v1",
              source_in_tick: 0,
              source_out_tick: 8000,
              playback_rate: 1,
              loop: false,
            },
            provenance_refs: ["asset-version:cat-video-v1"],
          },
          "r2v-window": {
            element_id: "r2v-window",
            label: "午饭名场面",
            enabled: true,
            span: { start_tick: 5000, duration_tick: 10000 },
            location: defaultLocation,
            z_index: 1,
            creation: {
              type: "r2v",
              intent: "生成猫咪隔窗看午饭的画面",
              narrative: "橘猫停下脚步看向窗内",
              continuity: "保持红色项圈",
              character_refs: ["cat"],
              scene_ref: null,
              prop_refs: [],
              visual_variant_refs: {
                cat: "variant:cat:default",
              },
              shots: {
                order: ["shot:window"],
                items: {
                  "shot:window": {
                    shot_id: "shot:window",
                    description: "橘猫隔窗看向午饭",
                    camera: "↑ 推近",
                    framing: "中景",
                    duration_seconds: 10,
                  },
                },
              },
              recipe: {
                provider: "dashscope",
                model: "wan2.7-r2v",
                seed: null,
                candidate_count: 1,
              },
              storyboard_prompt: "暖色餐厅窗外的橘猫",
              storyboard_reference_version_ids: ["cat-anchor-v1"],
              video_prompt: "镜头缓慢推近，橘猫眨眼",
              video_reference_version_ids: ["cat-anchor-v1"],
            },
            outputs: { video: { slot_id: "element:r2v-window:video" } },
            render_source: {
              type: "element_output",
              element_id: "r2v-window",
              output_name: "video",
              source_in_tick: 0,
              source_out_tick: null,
              playback_rate: 1,
              loop: false,
            },
            provenance_refs: ["artifact-version:cat-anchor-v1"],
          },
          "overlay-title": {
            element_id: "overlay-title",
            label: "开场标题 · 小猫出发",
            enabled: true,
            span: { start_tick: 1000, duration_tick: 5000 },
            location: { ...defaultLocation, y: 0.18, width: 0.6, height: 0.16 },
            z_index: 10,
            creation: {
              type: "overlay",
              text: "小猫出发",
              vibe: "轻快",
              prompt: "文字轻盈浮现",
              reference_version_ids: [],
              motion: {
                format: "html_css",
                html: "<!doctype html><html><body><div class='title'>小猫出发</div></body></html>",
                fps: 24,
                loop: true,
                design_notes: "标题轻盈浮现",
              },
            },
            outputs: {},
            render_source: null,
            provenance_refs: [],
          },
          "overlay-os": {
            element_id: "overlay-os",
            label: "小猫 OS · 午饭在哪里",
            enabled: true,
            span: { start_tick: 6000, duration_tick: 4500 },
            location: {
              ...defaultLocation,
              x: 0.72,
              y: 0.7,
              width: 0.42,
              height: 0.18,
            },
            z_index: 11,
            creation: {
              type: "overlay",
              text: "午饭在哪里？",
              vibe: "俏皮",
              prompt: "漫画气泡弹出",
              reference_version_ids: [],
            },
            outputs: {},
            render_source: null,
            provenance_refs: [],
          },
          "audio-bgm": {
            element_id: "audio-bgm",
            label: "轻快 Lo-fi BGM",
            enabled: true,
            span: { start_tick: 0, duration_tick: 20000 },
            location: null,
            z_index: -1,
            creation: {
              type: "audio",
              source_asset_version_id: "cat-video-v1",
              role: "bgm",
              gain_db: -6,
              pan: 0,
            },
            outputs: {},
            render_source: {
              type: "source_asset_version",
              version_id: "cat-video-v1",
              source_in_tick: 0,
              source_out_tick: 20000,
              playback_rate: 1,
              loop: false,
            },
            provenance_refs: ["asset-version:cat-video-v1"],
          },
          transition: {
            element_id: "transition",
            label: "晨光到午后的转场",
            enabled: true,
            span: { start_tick: 7000, duration_tick: 1000 },
            location: null,
            z_index: 20,
            creation: {
              type: "transition",
              from_element_id: "edit-opening",
              to_element_id: "r2v-window",
              transition_kind: "crossfade",
              easing: "ease-in-out",
            },
            outputs: {},
            render_source: null,
            provenance_refs: [],
          },
        },
      },
    },
  },
  assets: {
    files_by_id: {
      "file:source-video": {
        file_id: "file:source-video",
        kind: "source",
        relative_uri: "sources/cat.mp4",
        sha256: "sha-source",
        size_bytes: 1024,
        media_type: "video/mp4",
        created_at: "2026-07-20T00:00:00Z",
      },
      "file:cat-anchor": {
        file_id: "file:cat-anchor",
        kind: "artifact",
        relative_uri: "artifacts/cat.png",
        sha256: "sha-cat",
        size_bytes: 512,
        media_type: "image/png",
        created_at: "2026-07-20T00:00:10Z",
      },
      "file:r2v-video": {
        file_id: "file:r2v-video",
        kind: "artifact",
        relative_uri: "artifacts/window.mp4",
        sha256: "sha-r2v",
        size_bytes: 2048,
        media_type: "video/mp4",
        created_at: "2026-07-20T00:01:00Z",
      },
      "file:final": {
        file_id: "file:final",
        kind: "artifact",
        relative_uri: "artifacts/final.mp4",
        sha256: "sha-final",
        size_bytes: 4096,
        media_type: "video/mp4",
        created_at: "2026-07-20T00:02:00Z",
      },
    },
    source_versions_by_id: {
      "cat-video-v1": {
        version_id: "cat-video-v1",
        logical_asset_id: "asset:cat-video",
        name: "橘猫原始视频",
        file_id: "file:source-video",
        checksum: "sha-source",
        media_kind: "video",
        media_type: "video/mp4",
        provenance_refs: [],
        thumbnail_file_id: null,
        duration_seconds: 20,
        native_model_file_id: null,
        created_at: "2026-07-20T00:00:00Z",
        metadata: { description: "用户上传的橘猫素材" },
      },
    },
    intelligence_versions_by_id: {},
    artifact_slots_by_id: {
      "visual:cat:anchor": {
        slot_id: "visual:cat:anchor",
        kind: "visual_anchor",
        owner_ref: "visual-entity:cat",
        version_ids: ["cat-anchor-v1"],
        selected_version_id: "cat-anchor-v1",
        metadata: {},
      },
      "element:r2v-window:video": {
        slot_id: "element:r2v-window:video",
        kind: "element_video",
        owner_ref: "element:r2v-window",
        version_ids: ["r2v-window-v1"],
        selected_version_id: "r2v-window-v1",
        metadata: {},
      },
      "timeline:timeline:main:render": {
        slot_id: "timeline:timeline:main:render",
        kind: "timeline_render",
        owner_ref: "timeline:timeline:main",
        version_ids: ["final-v1"],
        selected_version_id: "final-v1",
        metadata: {},
      },
    },
    artifact_versions_by_id: {
      "cat-anchor-v1": {
        version_id: "cat-anchor-v1",
        slot_id: "visual:cat:anchor",
        kind: "visual_anchor",
        owner_ref: "visual-entity:cat",
        name: "橘猫角色锚点",
        file_id: "file:cat-anchor",
        checksum: "sha-cat",
        based_on_generation: 1,
        provenance_refs: ["asset-version:cat-video-v1"],
        thumbnail_file_id: null,
        duration_seconds: null,
        input_fingerprint: null,
        stale: false,
        stale_reason: null,
        created_at: "2026-07-20T00:00:10Z",
        metadata: {},
      },
      "r2v-window-v1": {
        version_id: "r2v-window-v1",
        slot_id: "element:r2v-window:video",
        kind: "element_video",
        owner_ref: "element:r2v-window",
        name: "午饭名场面视频",
        file_id: "file:r2v-video",
        checksum: "sha-r2v",
        based_on_generation: 2,
        provenance_refs: ["artifact-version:cat-anchor-v1"],
        thumbnail_file_id: null,
        duration_seconds: 10,
        input_fingerprint: null,
        stale: false,
        stale_reason: null,
        created_at: "2026-07-20T00:01:00Z",
        metadata: {},
      },
      "final-v1": {
        version_id: "final-v1",
        slot_id: "timeline:timeline:main:render",
        kind: "timeline_render",
        owner_ref: "timeline:timeline:main",
        name: "测试项目最终成片",
        file_id: "file:final",
        checksum: "sha-final",
        based_on_generation: 3,
        provenance_refs: ["artifact-version:r2v-window-v1"],
        thumbnail_file_id: null,
        duration_seconds: 20,
        input_fingerprint: null,
        stale: false,
        stale_reason: null,
        created_at: "2026-07-20T00:02:00Z",
        metadata: {},
      },
    },
  },
};
