# -*- coding: utf-8 -*-
# flake8: noqa: E501
# pylint: disable=line-too-long
"""Universal defect bank (tier-2): fixed near-miss questions per video.

Ported from APE-benchmark ``grader/rubrics/universal_defects.json`` (v3):
a hand-maintained question bank that is injected programmatically — never
generated by an LLM — so every reviewed video is measured with the same
ruler and results stay reproducible. Question polarity is near-miss
(ET = confirmed ABSENT, CT = present, NA = not applicable); an NA must
carry a reason and a CT must carry frame evidence, both enforced by the
parser (anti-hallucination).

The two rows that a program can evidence directly (shot count, freeze /
black screens) get their tier-0 facts attached as hints; the VLM still
issues the verdict on the focused frames.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, Mapping

Applicability = Literal["any", "real_subject", "has_person", "multi_shot"]


@dataclass(frozen=True, slots=True)
class UniversalDefect:
    """One bank question (upstream id kept for traceability)."""

    defect_id: str
    title: str
    question: str
    severity: Literal["minor", "major"]
    applicability: Applicability = "any"


# Upstream ids preserved (uq_* = per-case baseline questions).
UNIVERSAL_DEFECTS: tuple[UniversalDefect, ...] = (
    UniversalDefect(
        "uq_render_1",
        "花屏拼贴感",
        "请确认画面不存在花屏、马赛克块状损坏或多画面错位拼贴的痕迹。",
        "major",
    ),
    UniversalDefect(
        "uq_render_2",
        "空白帧",
        "请确认成片中段不存在整帧空白（纯白/纯灰无内容）的帧。",
        "major",
    ),
    UniversalDefect(
        "uq_render_3",
        "黑屏冻结",
        "请确认成片中段不存在异常黑屏或画面长时间冻结卡死（片尾定格收尾属正常收束，不算）。",
        "major",
    ),
    UniversalDefect(
        "uq_render_4",
        "局部花屏",
        "请确认画面局部区域不存在色块噪声、纹理撕裂等局部渲染损坏。",
        "major",
    ),
    UniversalDefect(
        "uq_subject_1",
        "跨镜主体漂移",
        "请确认同一主体（人物/动物/关键道具）在不同镜头间没有变脸、换装、发型或形态漂移（同人换角度、换景别不算漂移）。",
        "major",
        "multi_shot",
    ),
    UniversalDefect(
        "uq_subject_2",
        "肢体畸变",
        "请确认画面中人物不存在多指/缺指、面部扭曲、关节反折等解剖学畸变。",
        "major",
        "has_person",
    ),
    UniversalDefect(
        "uq_physics_1",
        "穿模悬浮",
        "请确认物体与人物不存在互相穿透、无支撑悬浮等违反物理常识的画面。",
        "minor",
        "real_subject",
    ),
    UniversalDefect(
        "uq_physics_2",
        "运镜卡顿",
        "请确认运镜过程平滑，不存在突然跳动、抖动或忽快忽慢的卡顿。",
        "minor",
    ),
    UniversalDefect(
        "uq_text_1",
        "文字乱码",
        "请确认画面中出现的所有文字（字幕/标题/招牌）清晰可读，不存在乱码、豆腐块或伪文字。",
        "major",
    ),
    UniversalDefect(
        "uq_text_2",
        "水印UI残留",
        "请确认画面不存在水印、平台 logo、进度条或其他 UI 元素残留。",
        "minor",
    ),
    UniversalDefect(
        "uq_transition_1",
        "跳切",
        "请确认镜头衔接不存在生硬跳切（同机位内容突跳）；有意的快切节奏不算。",
        "minor",
        "multi_shot",
    ),
    UniversalDefect(
        "uq_color_1",
        "色调跳变",
        "请确认相邻镜头之间色调/亮度一致，不存在无动机的色调跳变。",
        "minor",
        "multi_shot",
    ),
    UniversalDefect(
        "uq_ai_texture",
        "AI塑料质感",
        "请确认写实画面不存在明显的 AI 生成塑料感/过度平滑的皮肤与材质痕迹（动画/插画/风格化素材判 NA）。",
        "major",
        "real_subject",
    ),
    UniversalDefect(
        "uq_shot_count",
        "镜头数不足",
        "请对照计划镜头数确认成片实际镜头数没有明显不足（叠化转场会使程序刀数偏少，请以画面为准）。",
        "major",
        "multi_shot",
    ),
    UniversalDefect(
        "uq_image_quality",
        "局部模糊",
        "请确认画面主体区域不存在异常的局部失焦或涂抹模糊（背景景深虚化属正常）。",
        "minor",
    ),
    UniversalDefect(
        "uq_ending",
        "结尾截断",
        "请确认结尾不是硬截断：末帧画面/字幕没有停在半句话或动作进行到一半骤停。",
        "major",
    ),
)


def build_defect_question_block(*, multi_shot_expected: bool) -> str:
    """User-text section listing every applicable bank question."""
    lines = [
        "【固定缺陷题清单（universal defects，逐题判 ET/CT/NA）】",
        "以下为固定基线题库（近失误极性）：ET=确认无此缺陷，CT=确认存在（必须给出证据帧时间戳与修改建议），NA=不适用（必须给出理由）。",
        "适用性门控：动画/插画/强风格化素材对「AI塑料质感」「穿模悬浮」判 NA 并说明；画面中无人物时「肢体畸变」判 NA；单镜头视频对跨镜类题判 NA。",
    ]
    for defect in UNIVERSAL_DEFECTS:
        if not multi_shot_expected and defect.applicability == "multi_shot":
            continue
        lines.append(
            f"- {defect.defect_id}（{defect.title}，{defect.severity}）：{defect.question}",
        )
    return "\n".join(lines)


def program_defect_hints(
    objective_facts: Mapping[str, Any] | None,
) -> str:
    """Tier-0 evidence lines attached to their bank questions."""
    if not objective_facts:
        return ""
    lines: list[str] = []
    index = objective_facts.get("video_index") or {}
    if isinstance(index, Mapping):
        cut_count = index.get("cut_count")
        planned = index.get("planned_shot_count")
        if cut_count is not None:
            actual_shots = int(cut_count) + 1
            hint = f"程序检测到 {cut_count} 个切点（约 {actual_shots} 个镜头）"
            if planned:
                hint += f"，计划 {planned} 个镜头"
            lines.append(f"- uq_shot_count 证据：{hint}。")
        freezes = index.get("freeze_segments") or []
        if freezes:
            spans = ", ".join(
                f"{seg.get('start_ms')}–{seg.get('end_ms')}ms"
                for seg in freezes[:4]
                if isinstance(seg, Mapping)
            )
            lines.append(
                f"- uq_render_3 证据：程序检测到疑似静止段 {spans}" "（可能是合法定格，请看对应帧确认）。",
            )
    consistency = objective_facts.get("cross_shot_consistency") or {}
    if isinstance(consistency, Mapping):
        for pair in (consistency.get("suspect_pairs") or [])[:2]:
            if isinstance(pair, Mapping):
                lines.append(
                    "- uq_subject_1 证据：程序发现疑似主体不一致镜头对 "
                    f"t={pair.get('frame_a_ms')}ms vs t={pair.get('frame_b_ms')}ms"
                    "（同人换角度也会触发，请看画面确认）。",
                )
    if not lines:
        return ""
    return "【题库程序证据提示】\n" + "\n".join(lines)


__all__ = [
    "UNIVERSAL_DEFECTS",
    "UniversalDefect",
    "build_defect_question_block",
    "program_defect_hints",
]
